### ISSUE TITLE
Provide a method to retrieve the VSD release number

### ISSUE THREAD

**Issue by mboyerm** [nuagenetworks/java-bambou#11]
The enhancement is to provide a utility method which sends a GET request to VSD to retrieve the version number. Unfortunately there's no way to retrieve it currently from the API.spec (planned for future release) so in the interim let's look at getting the content of this file:

Here's an example:
curl -k https://aa.bb.cc.dd:<port>/Resources/app-version.js
APP_GITVERSION = 'r5.1-2a5b520'
APP_BUILDVERSION='5.1.2_73'

**Comment by pdumais** [comment]
Fixed with 95714cce6297ea220a25b68c3657f5451a3a8dfc
